# Generated by Django 5.2.13 on 2026-05-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrafficLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("predicted_label", models.CharField(max_length=100)),
                ("confidence", models.FloatField()),
                ("action", models.CharField(max_length=20)),
            ],
        ),
    ]
