# Generated by Django 5.2.13 on 2026-05-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ids_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trafficlog",
            name="source_ip",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="trafficlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("ALLOW", "Allow"),
                    ("BLOCK", "Block"),
                    ("MONITOR", "Monitor"),
                ],
                max_length=20,
            ),
        ),
    ]
