# Generated by Django 5.2.13 on 2026-05-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ids_app", "0002_trafficlog_source_ip_alter_trafficlog_action"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trafficlog",
            old_name="predicted_label",
            new_name="normalized_attack",
        ),
        migrations.RemoveField(
            model_name="trafficlog",
            name="action",
        ),
        migrations.RemoveField(
            model_name="trafficlog",
            name="source_ip",
        ),
        migrations.AddField(
            model_name="trafficlog",
            name="attack_count",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="trafficlog",
            name="decision",
            field=models.CharField(
                choices=[
                    ("ALLOW", "Allow"),
                    ("MONITOR", "Monitor"),
                    ("BLOCK", "Block"),
                    ("TEMP BAN", "Temporary Ban"),
                    ("CRITICAL ALERT", "Critical Alert"),
                ],
                default="0.0.0.0",
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trafficlog",
            name="explanation",
            field=models.TextField(default="Migration placeholder"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trafficlog",
            name="ip_address",
            field=models.CharField(default="0.0.0.0", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trafficlog",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trafficlog",
            name="original_attack",
            field=models.CharField(default="UNKNOWN", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trafficlog",
            name="recommendation",
            field=models.TextField(default="Migration placeholder"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trafficlog",
            name="repeat_offender",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trafficlog",
            name="severity",
            field=models.CharField(
                choices=[
                    ("LOW", "Low"),
                    ("MEDIUM", "Medium"),
                    ("HIGH", "High"),
                    ("CRITICAL", "Critical"),
                ],
                default="LOW",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
